[build]
  publish = "."
  command = "echo 'No build command needed - static site'"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Ensure JS files are served with correct MIME type
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/js/*"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

# Ensure all files in js directory are included
[[headers]]
  for = "/js/index.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"